In [ ]:
#Create a Dictionary with Academic Details
dict={
    "name":"Shihab Khan",
    "marks": 90,
    "roll No": 55
}
print(dict)

{'name': 'Shihab Khan', 'marks': 90, 'roll No': 55}


In [ ]:
#Create a list and find mean
l=[1,2,3,4,5]
mean=sum(l)/len(l)
print(mean)

3.0


In [ ]:
#Sum of 5 natural numbers
n=5
s=0

for i in range(1,6):
  s=s+i
print(s)


15


In [ ]:
import numpy as np

In [ ]:
npl = np.array(l)
print(npl)
npl.mean()

[1 2 3 4 5]


np.float64(3.0)

In [ ]:
npl[-2]

np.int64(4)

In [ ]:
#Slicin
npl[0:2]

array([1, 2])

In [ ]:
a=np.zeros((3,3))
print(a)
b=np.ones((2,4))
print(b)
c=np.eye(3)
print(c)
d=np.arange(0,10,2)
print(d)
e=np.linspace(0,1,5)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 3)
2
9
float64


In [ ]:
#1D INDEXING
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
#2D SLICING
m=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
print(m[0,1])
print(m[0:2,1:])
print(m[:,0])
print(m[1,:])

2
[[2 3]
 [5 6]]
[1 4 7]
[4 5 6]


In [ ]:
#
arr=np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr[[0,2,4]])
print(arr[np.where(arr<35)])

[30 40 50]
[10 30 50]
[10 20 30]


In [ ]:
arr=np.array([10,20,30,40,50])