In [30]:
import numpy as np


In [29]:
mylist=[10,20,30,40,50]
array=np.array(mylist)
print(array)

[10 20 30 40 50]


In [28]:
nums=np.arange(1,8)
print(nums)


[1 2 3 4 5 6 7]


In [26]:
nums=np.arange(1,10,2)
print(nums)

[1 3 5 7 9]


In [27]:
array=np.arange(0.0,1.0)
print(array)

[0.]


In [25]:
d=np.linspace(5,8,18)
print(d)

[5.         5.17647059 5.35294118 5.52941176 5.70588235 5.88235294
 6.05882353 6.23529412 6.41176471 6.58823529 6.76470588 6.94117647
 7.11764706 7.29411765 7.47058824 7.64705882 7.82352941 8.        ]


In [24]:
data=np.array([[1,2,3],[4,5,6]])
print(data)

[[1 2 3]
 [4 5 6]]


In [23]:
np.arange?

In [22]:
scores=np.array([98,78,89,67,90,85,45,55,100])
print(scores[scores<60])

[45 55]


In [21]:
ages=np.array([45,13,24,50,67,99,96,100])
teenagers=ages[ages<18]
adults=ages[(ages>=18) & (ages<65)]
seniors=ages[(ages>=65) & (ages<=100)]
print(teenagers)
print(adults)
print(seniors)

[13]
[45 24 50]
[ 67  99  96 100]


In [19]:
d=np.array([11,12,13,14,15])
print(d**2)

[121 144 169 196 225]


In [20]:
print(d**2-1)

[120 143 168 195 224]


In [18]:
d1=np.array([20,120,39,20])
d2=np.array([20,10,40,50])
print(d1*d2)

[ 400 1200 1560 1000]


In [17]:
print(d1.shape)
print(d1.ndim)
print(d1.size)
print(d1.dtype)
print(d1.itemsize)
print(d1.nbytes)


(4,)
1
4
int64
8
32


In [16]:
n=np.fromstring('10 20 30 40 50',dtype=np.float16,sep=' ')
print(n)
print(n.dtype, type(n))

[10. 20. 30. 40. 50.]
float16 <class 'numpy.ndarray'>


In [34]:
%%time
my_list=[10,20,30,40,50]
list2=[2*m for m in my_list]
#print(list2)

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 11.7 µs


In [35]:
%%time
my_array=np.array([10,20,30,40,50])
new_array=my_list*2
#print(new_array)

CPU times: user 19 µs, sys: 2 µs, total: 21 µs
Wall time: 24.1 µs


In [32]:
nzeroes=np.zeros((3,4), dtype=np.int16)
print(nzeroes)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
nones=np.ones((3,4), dtype=np.int16)
print(nones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [36]:
scores=np.array([98,78,89,67,90,85,45,55,100])
print(scores.min())
print(scores.max())
print(scores.sum())
print(scores.mean())
print(scores.var())
print(scores.argmax())
print(scores.argmin())

45
100
707
78.55555555555556
326.0246913580247
8
6
